// =====================================================================
// UI TEXT
// Words used on buttons, headings and labels across the whole site.
// (The content of each guide lives in the /guides folder instead.)
//
// Every entry has an English (en) and Urdu (ur) version.
// To change a word, just edit the text between the quotes.
// =====================================================================

const UI = {
  siteName:     { en: "Rahnuma", ur: "رہنما" },
  tagline:      { en: "Simple guides for getting government documents made in Pakistan",
                  ur: "سرکاری کاغذات بنوانے کے لیے آسان رہنمائی" },
  switchLang:   { en: "اردو", ur: "English" },

  // Home page
  searchLabel:  { en: "What do you need to get made?", ur: "آپ کو کیا بنوانا ہے؟" },
  searchHint:   { en: "e.g. ID card, passport, domicile", ur: "مثلاً شناختی کارڈ، پاسپورٹ، ڈومیسائل" },
  noResults:    { en: "Nothing found. Try a different word, or look through the list below.",
                  ur: "کچھ نہیں ملا۔ کوئی اور لفظ لکھ کر دیکھیں یا نیچے دی گئی فہرست دیکھیں۔" },
  quickLinks:   { en: "Most needed", ur: "سب سے زیادہ ضرورت" },
  topics:       { en: "Choose a topic", ur: "موضوع منتخب کریں" },
  allTopics:    { en: "All topics", ur: "تمام موضوعات" },
  guidesCount:  { en: "guides", ur: "صفحات" },
  allPakistan:  { en: "All Pakistan", ur: "پورا پاکستان" },
  punjab:       { en: "Punjab", ur: "پنجاب" },
  aboutTitle:   { en: "About Rahnuma", ur: "رہنما کے بارے میں" },
  aboutText:    { en: "Rahnuma is a free, volunteer-run website that explains, in simple words, which documents you need, what it costs, and where to go for common government services. It is not a government website. It does not collect any of your information, unless you choose to send us feedback.",
                  ur: "رہنما ایک مفت اور رضاکارانہ ویب سائٹ ہے جو آسان الفاظ میں بتاتی ہے کہ عام سرکاری کاموں کے لیے کون سے کاغذات چاہییں، کتنی فیس لگتی ہے اور کہاں جانا ہے۔ یہ سرکاری ویب سائٹ نہیں ہے۔ یہ آپ کی کوئی معلومات جمع نہیں کرتی، سوائے اس کے جو آپ خود رائے کے طور پر بھیجیں۔" },

  // Guide page
  back:         { en: "All guides", ur: "تمام معلومات" },

  // Jump-button names on the guide page (keep them short – they sit side by side)
  tabSummary:   { en: "Summary", ur: "خلاصہ" },
  tabWho:       { en: "Who can apply", ur: "کون اہل ہے" },
  tabDetails:   { en: "Details", ur: "تفصیل" },
  tabDocuments: { en: "Documents", ur: "کاغذات" },
  tabSteps:     { en: "Steps", ur: "طریقہ" },
  tabFees:      { en: "Fee", ur: "فیس" },
  tabWhere:     { en: "Where", ur: "کہاں" },
  tabTips:      { en: "Tips", ur: "مشورے" },
  tabSources:   { en: "Sources", ur: "ذرائع" },

  eligibility:  { en: "Who can apply", ur: "کون درخواست دے سکتا ہے" },
  notEligible:  { en: "Who cannot apply", ur: "کون اہل نہیں" },
  lastChecked:  { en: "Last checked:", ur: "آخری بار جانچ:" },
  disclaimer:   { en: "Fees and rules can change. Please confirm with the office or official website before you go.",
                  ur: "فیس اور قوانین بدل سکتے ہیں۔ جانے سے پہلے متعلقہ دفتر یا سرکاری ویب سائٹ سے تصدیق کر لیں۔" },
  priceNote:    { en: "💬 Prices change from time to time, and the prices on this website may not be fully up to date. Please confirm the current fee at the office or on the official website before paying.",
                  ur: "💬 قیمتیں وقتاً فوقتاً بدلتی رہتی ہیں اور اس ویب سائٹ پر دی گئی قیمتیں مکمل طور پر تازہ ترین نہیں بھی ہو سکتیں۔ ادائیگی سے پہلے دفتر یا سرکاری ویب سائٹ سے موجودہ فیس کی تصدیق کر لیں۔" },
  notes:        { en: "Please note", ur: "براہِ کرم نوٹ کریں" },
  documents:    { en: "Documents you need", ur: "ضروری کاغذات" },
  documentsTip: { en: "Tick each one when you have it ready.", ur: "جو کاغذ تیار ہو جائے اس پر نشان لگا لیں۔" },
  steps:        { en: "Step by step", ur: "مرحلہ وار طریقہ" },
  fees:         { en: "Fee and time", ur: "فیس اور وقت" },
  where:        { en: "Where to go", ur: "کہاں جائیں" },
  contacts:     { en: "Helpline and websites", ur: "ہیلپ لائن اور ویب سائٹ" },
  mistakes:     { en: "Common mistakes to avoid", ur: "ان غلطیوں سے بچیں" },
  faqs:         { en: "Common questions", ur: "عام سوالات" },
  related:      { en: "Related guides", ur: "متعلقہ معلومات" },
  sources:      { en: "Where this information comes from", ur: "یہ معلومات کہاں سے لی گئیں" },
  share:        { en: "Send this page on WhatsApp", ur: "یہ صفحہ واٹس ایپ پر بھیجیں" },
  notFound:     { en: "Sorry, this guide was not found.", ur: "معذرت، یہ صفحہ نہیں ملا۔" },
  loading:      { en: "Loading…", ur: "لوڈ ہو رہا ہے…" },
  free:         { en: "Free", ur: "مفت" },

  // Feedback page (feedback.html)
  fbFooterLink:       { en: "Give feedback or report a mistake",
                      ur: "رائے دیں یا غلطی کی نشاندہی کریں" },
  fbReportThisPage:   { en: "Something wrong or out of date on this page? Tell us.",
                      ur: "اس صفحے پر کچھ غلط یا پرانا ہے؟ ہمیں بتائیں۔" },
  fbTitle:            { en: "Feedback",
                      ur: "آپ کی رائے" },
  fbIntro:            { en: "Your feedback helps us make Rahnuma better for everyone. It only takes a minute.",
                      ur: "آپ کی رائے سے ہم رہنما کو سب کے لیے بہتر بناتے ہیں۔ اس میں صرف ایک منٹ لگتا ہے۔" },
  fbTabFeedback:      { en: "Give feedback",
                      ur: "رائے دیں" },
  fbTabReport:        { en: "Report a change",
                      ur: "تبدیلی کی اطلاع دیں" },
  fbTopic:            { en: "What did you want help with?",
                      ur: "آپ کو کس چیز میں مدد چاہیے تھی؟" },
  fbChoose:           { en: "Choose…",
                      ur: "منتخب کریں…" },
  fbOther:            { en: "Something else / not on this list",
                      ur: "کچھ اور / اس فہرست میں نہیں" },
  fbSatisfaction:     { en: "How satisfied are you with Rahnuma?",
                      ur: "آپ رہنما سے کتنے مطمئن ہیں؟" },
  fbSat1:             { en: "Very unhappy",
                      ur: "بہت ناخوش" },
  fbSat2:             { en: "Unhappy",
                      ur: "ناخوش" },
  fbSat3:             { en: "Okay",
                      ur: "ٹھیک ہے" },
  fbSat4:             { en: "Happy",
                      ur: "خوش" },
  fbSat5:             { en: "Very happy",
                      ur: "بہت خوش" },
  fbComments:         { en: "Anything else you'd like to tell us?",
                      ur: "کچھ اور بتانا چاہیں گے؟" },
  fbOptional:         { en: "optional",
                      ur: "اختیاری" },
  fbWhichPage:        { en: "Which guide has wrong or old information?",
                      ur: "کس صفحے پر غلط یا پرانی معلومات ہے؟" },
  fbWhatWrong:        { en: "What has changed? (tick all that apply)",
                      ur: "کیا بدل گیا ہے؟ (جتنے لاگو ہوں سب پر نشان لگائیں)" },
  fbPartFee:          { en: "Fee or price",
                      ur: "فیس یا قیمت" },
  fbPartDocs:         { en: "Documents needed",
                      ur: "ضروری کاغذات" },
  fbPartSteps:        { en: "Steps / process",
                      ur: "طریقہ کار" },
  fbPartTime:         { en: "Time it takes",
                      ur: "لگنے والا وقت" },
  fbPartOffice:       { en: "Office, address or timings",
                      ur: "دفتر، پتہ یا اوقات" },
  fbPartContact:      { en: "Phone number or website",
                      ur: "فون نمبر یا ویب سائٹ" },
  fbPartOther:        { en: "Something else",
                      ur: "کچھ اور" },
  fbDetails:          { en: "What is wrong, and what is correct now?",
                      ur: "کیا غلط ہے، اور اب درست کیا ہے؟" },
  fbDetailsHint:      { en: "For example: “The page says the fee is Rs 400, but at the NADRA office in Jaranwala it was Rs 750 in September 2026.”",
                      ur: "مثلاً: “صفحے پر فیس 400 روپے لکھی ہے، لیکن ستمبر 2026 میں جڑانوالہ کے نادرا دفتر میں 750 روپے تھی۔”" },
  fbSource:           { en: "How do you know?",
                      ur: "آپ کو کیسے معلوم ہوا؟" },
  fbSrcVisited:       { en: "I went to the office myself recently",
                      ur: "میں حال ہی میں خود دفتر گیا / گئی" },
  fbSrcOfficial:      { en: "Official website, notice or helpline",
                      ur: "سرکاری ویب سائٹ، نوٹس یا ہیلپ لائن" },
  fbSrcHeard:         { en: "Someone told me",
                      ur: "کسی نے بتایا" },
  fbSrcOther:         { en: "Other",
                      ur: "کوئی اور ذریعہ" },
  fbContact:          { en: "Your name or phone number, if you're happy for us to contact you",
                      ur: "اپنا نام یا فون نمبر، اگر آپ چاہتے ہیں کہ ہم رابطہ کریں" },
  fbContactHint:      { en: "You can leave this empty. We only use it to ask about your report.",
                      ur: "آپ اسے خالی چھوڑ سکتے ہیں۔ ہم اسے صرف آپ کی اطلاع کے بارے میں پوچھنے کے لیے استعمال کریں گے۔" },
  fbPrivacy:          { en: "Please don't write your CNIC number, passwords or other private details.",
                      ur: "براہِ کرم اپنا شناختی کارڈ نمبر، پاس ورڈ یا دوسری ذاتی معلومات نہ لکھیں۔" },
  fbSend:             { en: "Send",
                      ur: "بھیجیں" },
  fbSending:          { en: "Sending…",
                      ur: "بھیجا جا رہا ہے…" },
  fbNeedTopic:        { en: "Please choose what you wanted help with.",
                      ur: "براہِ کرم منتخب کریں کہ آپ کو کس چیز میں مدد چاہیے تھی۔" },
  fbNeedSatisfaction: { en: "Please choose how satisfied you are.",
                      ur: "براہِ کرم بتائیں کہ آپ کتنے مطمئن ہیں۔" },
  fbNeedGuide:        { en: "Please choose which guide needs changing.",
                      ur: "براہِ کرم منتخب کریں کہ کس صفحے میں تبدیلی چاہیے۔" },
  fbNeedDetails:      { en: "Please write what is wrong and what is correct.",
                      ur: "براہِ کرم لکھیں کہ کیا غلط ہے اور کیا درست ہے۔" },
  fbThanksTitle:      { en: "Thank you!",
                      ur: "شکریہ!" },
  fbThanksFeedback:   { en: "We've received your feedback.",
                      ur: "ہمیں آپ کی رائے مل گئی ہے۔" },
  fbThanksReport:     { en: "We've received your report. We'll check it and update the guide.",
                      ur: "ہمیں آپ کی اطلاع مل گئی ہے۔ ہم اسے جانچ کر صفحہ اپ ڈیٹ کریں گے۔" },
  fbEmailFallback:    { en: "We couldn't send this online. You can send it by email instead:",
                      ur: "ہم یہ آن لائن نہیں بھیج سکے۔ آپ اسے ای میل کے ذریعے بھیج سکتے ہیں:" },
  fbEmailButton:      { en: "Send by email",
                      ur: "ای میل سے بھیجیں" },
  fbCantSend:         { en: "Sorry, your message could not be sent right now. Please check your internet and try again later.",
                      ur: "معذرت، ابھی آپ کا پیغام نہیں بھیجا جا سکا۔ انٹرنیٹ چیک کر کے بعد میں دوبارہ کوشش کریں۔" },

  footer:       { en: "Rahnuma is a volunteer community project, not a government website.",
                  ur: "رہنما ایک رضاکارانہ فلاحی منصوبہ ہے، سرکاری ویب سائٹ نہیں۔" }
};

const MONTHS = {
  en: ["January", "February", "March", "April", "May", "June", "July",
       "August", "September", "October", "November", "December"],
  ur: ["جنوری", "فروری", "مارچ", "اپریل", "مئی", "جون", "جولائی",
       "اگست", "ستمبر", "اکتوبر", "نومبر", "دسمبر"]
};
